spring:
  application:
    name: EyeApp
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  logging:
    level:
      ROOT: INFO
      org:
        springframework:
          web:
            server:
              adapter:
                HttpWebHandlerAdapter: TRACE

springdoc:
  default-produces-media-type: application/json

server:
  port: 8092
  servlet:
    context-path: /api/