services:
  postgres:
    #À adapter avec le nom du projet
    container_name: postgres-starter-perso-app-jwt
    image: postgres
    environment:
      #À mettre dans le fichier .env
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      #À adapter avec le nom du projet
      POSTGRES_DB: StarterPersoAppJwt
    volumes:
      - postgres:/data/postgres
    ports:
      #public:container
      - 5432:5432
    networks:
      #À adapter avec le nom du projet
      - starter-perso-app-jwt
    restart: unless-stopped
  mail-dev:
    #À adapter avec le nom du projet
    container_name: mail-starter-perso-app-jwt
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  #À adapter avec le nom du projet
  starter-perso-app-jwt:
    driver: bridge

volumes:
  postgres:
    driver: local